### ISSUE TITLE
joining rbind

### ISSUE THREAD

**Issue by homerhanumat** [rbind/support#24]
I would like to join **rbind**. 

I don't think I need any help setting up sites, but would like to go through the process of joining **rbind** and to keep on experimenting with blogdown -- which I have been using for a while -- with a view to becoming able to advise others, especially my own students in the coming academic year.

Can I get an invitation email?

Netlify sudomain:  singer-alvin-24383
Preferred rbind subdomain:  homerhanumat

Thanks,
Homer

**Comment by yihui** [comment]
Sure. The invitation has been sent, and the subdomain has been assigned. You need to fill out the custom domain homerhanumat.rbind.io on Netlify. Please feel free to transfer your repo to rbind after you accept the invitation. Thanks!

**Comment by homerhanumat** [comment]
Done.  Thanks!

**Comment by yihui** [comment]
It seems the URL http://homerhanumat.rbind.io still does not work for me. Did you use the button "Configure domain" on Netlify?

![image](https://cloud.githubusercontent.com/assets/163582/26532991/e3e5bb40-4453-11e7-9bbb-ad54f5e14d09.png)

**Comment by homerhanumat** [comment]
It seems I had forgotten to go back and configure the domain and to enable https.  It now works for me at:

>[https://homerhanumat.rbind.io](https://homerhanumat.rbind.io)

**Comment by yihui** [comment]
Yep, works now.

**Comment by homerhanumat** [comment]
By the way (I'm not sure where to post this observation, but I saw your Rbind post in whihc you express a dislike for Disqus) there is a way to use Github Issues as the locus for comments.  You pull them down with a GEt request to the Github Issues api.  I have implemented them on my other **blogdown** site, see, e.g.:

>[https://homerhanumat.github.io/post/2015-12-15-jekyll-r-blogger-knitr-hyde/](https://homerhanumat.github.io/post/2015-12-15-jekyll-r-blogger-knitr-hyde/)

The comments on the above post link to the post of the Don Williamson, the person who discovered this hack.  Not sure how widely it should spread, though (see comments on Don's post).

**Comment by yihui** [comment]
Thanks! I was aware of Don's post. While I love the fact that one can use Markdown, I don't like the fact that one has to jump to Github to write comments. If there are too many comments, it may not be straightforward to fetch all of them via the Github API at once.
